Add keywords
CovOpen/CovMapper pull request #189
Opened 2020-10-22 08:33 UTC by alexanderthieme

2020-10-22 15:04 UTC, kommander commented on apps/official/build.json
> +    "keywords": "CovMap, Corona, Coronavirus, Vorhersage, Regionales Risiko"
```suggestion
    "description": "Tool zur Visualisierung von epidemiologischen Daten und Frühindikatoren des SARS-CoV-2 Infektionsgeschehens",
    "keywords": "CovMap, Corona, Coronavirus, Vorhersage, Regionales Risiko"
```

2020-10-22 15:05 UTC, kommander requested changes
@DanielHabenicht Schreiben wir die Keywords gerade auch ins HTML mit dem WebpackHTMLPlugin dingens?

2020-10-22 15:15 UTC, DanielHabenicht commented
@kommander keine ahnung, hatte nur die description angepackt

2020-10-24 12:41 UTC, DanielHabenicht approved these changes

2020-10-24 13:50 UTC, kommander approved these changes

2020-10-24 13:51 UTC, merged